### ISSUE TITLE
Sprint in build phase

### ISSUE THREAD

**Issue by arenaceous** [TheZoc/sourceforts-bug-tracker#93] opened 2019-01-30 07:29 UTC
If the combat phase is left with 0 sprint in your meter, you will have no sprint in the build phase. (Possibly also a problem in the reverse phase transition)

**Comment by TheZoc** [comment] 2019-02-01 01:34
Can you give exact reproduction steps for this?
(Please, don't make me attempt to finish combat phase with no energy, it will take ages to reproduce ahaah :(  )

**Comment by TheZoc** [comment] 2019-02-18 22:48
This is probably related to #99

**Comment by Melectrome** [comment] 2019-02-22 18:07
I closed my infinite sprint bug issue for this as I found a proper way to reproduce all of the bugs in my old issue and this issue.
To get infinite sprint:
1. At the end of buildphase hold sprint and move around until the combat phase starts
2. Infinite sprint.

With infinite sprint you get the
`DataTable warning: player: Out-of-range value (267.076508/100.000000) in SendPropFloat 'm_flSuitPower', clamping.`
warnings if you're standing still while holding the sprint button, and also if you die while sprinting.

This is related to this issue because it occurs in the same way:
1. Drain your sprint to very low
2. `togglephase` in console
3. Badaboom very little sprint in build phase
4. And if combat phase starts you get much less sprint (your sprint limit is equal to the sprint remaining you had when the first combat phase changed to build phase)

**Comment by TheZoc** [comment] 2019-03-11 22:03
Due to the nature of this bug, I added a fix that prevents stamina from being drained at all during the build phase - it shouldn't be actually draining it anyway.

This will fix the "no sprint" during build phase.

If the extra stamina was being added due that, when switching phases, this fix will fix the infinite sprint bug.
Please, pay special attention to server logs!

This fix was added to RC6

**Comment by metenn** [comment] 2019-05-03 19:52
Still doesn't fix.
The only thing I noticed is that the error messages spam less than they used to.

**Comment by TheZoc** [comment] 2019-05-18 01:17
Fixed in RC7 😁 
(Also, this fixes #99)

**Closed as completed by TheZoc** 2019-05-18 01:17 UTC
