### ISSUE TITLE
­

### ISSUE THREAD

**Issue by Nick12506** [TheZoc/sourceforts-bug-tracker#13] opened 2018-10-17 07:41 UTC
![beta](https://user-images.githubusercontent.com/11761833/47070055-77480480-d1be-11e8-8b91-63a200bcc884.png)

**Comment by Melectrome** [comment] 2018-10-17 18:55
Duplicate of [#10](https://github.com/TheZoc/sourceforts-bug-tracker/issues/5)

**Comment by Melectrome** [comment] 2018-10-17 18:56
This can be fixed by forcing a random (or the same map) string for the `nextlevel` cvar upon the map being loaded

**Comment by Melectrome** [comment] 2018-10-17 18:57
Or by just completely ignoring it and adding a mapcycle.txt file to /cfg/ ;p

**Closed as completed** 2018-10-18 00:44 UTC
